### ISSUE TITLE
Feature Request : Add text to grid

### ISSUE THREAD

**Issue by INTstinkt** [Yinzo/sd-webui-Lora-queue-helper#11]
Would be nice if you would be able to see which lora was used for each picture in the grid similar to "test my prompt" extrention from Extraltodeus.

**Comment by tetsuoo-online** [comment]
> Would be nice if you would be able to see which lora was used for each picture in the grid similar to "test my prompt" extrention from Extraltodeus.

Funny, I added that today and I didn't see your comment yesterday. Incredible xD
https://github.com/Yinzo/sd-webui-Lora-queue-helper/issues/9
