### ISSUE TITLE
TypeError after update.

### ISSUE THREAD

**Issue by lithodora** [Yinzo/sd-webui-Lora-queue-helper#4]
Using Automatic1111 version: [1.6.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/03eec1791be011e087985ae93c1f66315d5a250e) and python: 3.10.6.

I opened the Extensions and checked for updates. Lora Queue Helper was the only update. I applied and restarted.
When I tried to use the script I get:

`TypeError: Script.run() missing 9 required positional arguments: 'is_use_custom_path', 'custom_path', 'directories', 'selected_loras', 'checkbox_iterate', 'checkbox_iterate_batch', 'is_save_grid', 'is_auto_row_number', and 'row_number'`

I used the Backup/Restore to roll back the change to commit [be67ef53](https://github.com/Yinzo/sd-webui-Lora-queue-helper/commit/be67ef5331865ab255d4d1b6acfc49622b43c334)

And now get a slightly different error, but the same issue: 

`TypeError: Script.run() missing 7 required positional arguments: 'is_use_custom_path', 'custom_path', 'directories', 'selected_loras', 'checkbox_iterate', 'checkbox_iterate_batch', and 'is_save_grid'`

I tried to manually remove the folder and update manually, but get the same issue regardless.

**Comment by Yinzo** [comment]
Thanks for reporting. I tried to check out A1111 to your specified commit, but it seems not  exist on the master branch of A1111.

The A1111 commit I am using is [the current master](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7), and it works fine on my local environment.
Based on the error log you attached, it shows that all the parameters are missing, which is nearly impossible under normal circumstances. But gradio did a poor job with error traceback, so I can't say it's impossible.

But I need more information to fix your issue.

Could you go to the A1111 directory and check `git status`? If it's normal, then go to `{A1111 directory}/extensions/sd-webui-Lora-queue-helper` and also check `git status` there. You can post them here if you can't decide if it's correct.

And maybe attach more of the error log, the whole log is better, as there could be some useful information at the very beginning of the error log.

**Comment by Yinzo** [comment]
And more version information is helpful, you can copy it from the bottom of your a1111 webui. Here is mine:

version: v1.6.1-3-ga254ce80  •  python: 3.11.5  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: c3056f6175

The difference on python version should not cause this issue, I am thinking of gradio version issue.

**Comment by lithodora** [comment]
version: [1.6.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/03eec1791be011e087985ae93c1f66315d5a250e)  •  python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [0f1b80cfe8](https://google.com/search?q=0f1b80cfe81b9c3bde7fdcbf6898897b2811b27be1df684583c3d85cbc9b1fa4)


To be clear I am running [Stable Diffusion web UI with DirectML](https://github.com/lshqqytiger/stable-diffusion-webui-directml)
Have an AMD card 
```

stable-diffusion-webui-directml>git status
Refresh index: 100% (323/323), done.
On branch master
Your branch is up to date with 'origin/master'.
```


```
stable-diffusion-webui-directml\extensions\sd-webui-Lora-queue-helper>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Interestingly the script was working perfectly earlier today. 
After the update I got the error and there seems to be no going back. 

I have plenty of space, so I'm going to try a fresh install and will check back in with an update.

**Comment by lithodora** [comment]
New install and it works fine. 

I've saved detailed steps on how to do my setup so in 12 minutes it was back up and running.

The installed version that encountered the issue exists and can be run to see if we can correct the issue is desired. 
Otherwise we can close this issue and chalk it up to localization issues.

**Comment by Yinzo** [comment]
So you set up a new stable-diffusion-webui-directml environment and it works now? 
At least you can use SD without errors now. 

That might be an issue specific to directml version. It could be due to some random reason, like a bug in the required packages at a specific version causing that problem.

I don't have that environment to test, so I think I will leave this issue open for some time and see if there are other people  who encounter this problem. If not, we can just forget it. ;)
