### ISSUE TITLE
Enhancement? The ability to use multiple Loras for even more dynamic results?

### ISSUE THREAD

**Issue by DooDip** [Yinzo/sd-webui-Lora-queue-helper#5]
I'm not sure how hard it would be to implement, but the idea of being able to run multiple Loras from the list at a time would be pretty cool. I am not a programmer and I am new to AI, so I am unsure how the process works in the software. I've used multiple Loras in my prompts and it can create some pretty cool styles and effects.

Thanks!

**Comment by Yinzo** [comment]
I am not sure exactly what you want.
let's say we have four Loras: A, B, C, and D. 
Do you want to use these 4 Loras to generate one image, or you want to create four separate images, each for A, B, C, and D? 

The former can be achieved just by using a normal prompt containing all four Loras. The latter is what this script currently does. 

Therefore, I am unclear about your request. Could you please provide more information or examples?

**Comment by DooDip** [comment]
4 Loras to create 1 image. I realize this is possible using a normal prompt, but running random Loras in a batch would be pretty cool.

**Comment by Yinzo** [comment]
Well maybe checkout [dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) and [wildcards](https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards), they can help you using random prompt in a file, maybe it can also use on lora.
