### ISSUE TITLE
Problem : Grid do not save (+feature request)

### ISSUE THREAD

**Issue by tetsuoo-online** [Yinzo/sd-webui-Lora-queue-helper#9]
I love this script it's really something I needed, Auto row number is a simple but very nice feature too. BUT...

- the grid is not saving. I can find it in appdata/local/temp/gradio then I copy that somewhre manually but it's not cool
- it would be nice to have the lora names in the grid, because if a lot are tested it quickly become difficult to tell what lora was used for each image
 I'm using webUI Forge :
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7

```
Thank you

**Comment by tetsuoo-online** [comment]
So~ today I decided to use Claude AI to add the option I want. It works nicely :)
For those who wanna try, here you go : [scripts.zip](https://github.com/user-attachments/files/16043760/scripts.zip), place the files in extensions\sd-webui-Lora-queue-helper\scripts folder. 
There is now options to get lora names on each image on the grid. There's still no automatic save for the grid because I forgot x)
I spent the night on this so I need to sleep, maybe I will add that later (maybe not).



![image](https://github.com/Yinzo/sd-webui-Lora-queue-helper/assets/45845308/847157a3-1f5b-4137-b48b-b788b5eac687)
![image](https://github.com/Yinzo/sd-webui-Lora-queue-helper/assets/45845308/94dd4e33-29c0-44bc-b54b-db40af457869)

**Comment by Yinzo** [comment]
> So~ today I decided to use Claude AI to add the option I want. It works nicely :) For those who wanna try, here you go : [scripts.zip](https://github.com/user-attachments/files/16043760/scripts.zip), place the files in extensions\sd-webui-Lora-queue-helper\scripts folder. There is now options to get lora names on each image on the grid. There's still no automatic save for the grid because I forgot x) I spent the night on this so I need to sleep, maybe I will add that later (maybe not).
> 
> ![image](https://private-user-images.githubusercontent.com/45845308/344453469-847157a3-1f5b-4137-b48b-b788b5eac687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTA5NDgsIm5iZiI6MTcxOTgxMDY0OCwicGF0aCI6Ii80NTg0NTMwOC8zNDQ0NTM0NjktODQ3MTU3YTMtMWY1Yi00MTM3LWI0OGItYjc4OGI1ZWFjNjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA1MTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjI5YjExODczNGRlZWU4YTBlNGNmNDA3MzFiZTYzNGFmNDAxMzc4M2ZiOWNlM2Y4MmUzYWFlOTYyZTQ4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-e2Xmz_S5O3jAuGfOTNxqOwd3UdOtwz-5e89id39914) ![image](https://private-user-images.githubusercontent.com/45845308/344454786-94dd4e33-29c0-44bc-b54b-db40af457869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTA5NDgsIm5iZiI6MTcxOTgxMDY0OCwicGF0aCI6Ii80NTg0NTMwOC8zNDQ0NTQ3ODYtOTRkZDRlMzMtMjljMC00NGJjLWI1NGItZGI0MGFmNDU3ODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA1MTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NjliMTFiYTdmZjY0NjQ3Yjk2ZmJkODg3OTg2MjY1NmQ2NTdjNGI4NTExZWFhMDJkOTI5YWU2MTFmZjg3YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U5jGejiyshIchrvQ4WTLt_6VrjXTHajulmzB8qo0fyM)

Nice job! I would love to merge your update into the plugin repo, you can create a Pull Request if you want!

**Comment by tetsuoo-online** [comment]
> Nice job! I would love to merge your update into the plugin repo, you can create a Pull Request if you want!

Sorry I completely forgot to come back earlier ^^;
Ok I think I managed to add a Pull Request... I hope there's no mistake, I have never done that before xD So that was completely alien to me lol
